---
title: "Introduction au tidyverse"
author: "Jocelyn Béziau"
date: "`r format(Sys.Date(),'%d %B %Y')`"
categories: ["R", "tidyverse"]
tags: ["R", "tidyverse", "formation", "intro"]
---
    
```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```
    
# Un touR du monde commence par un premier pas

* [tidyverse](https://www.tidyverse.org/packages/) = core (chargés par défaut lors de `library(tidyverse)` : `ggplot2`, `dplyr`, `tidyr`, `readr`, `purrr`, `tibble`, `stringr` et `forcats`) + extended (doivent être chargés séparément : `lubridate`, `hms`, `blob`, `dbplyr`, `dtplyr`, `magrittr`, `glue`, `tidymodels` et DBI/haven/httr/readxl/googlesheets4/googledrive/rvest/jsonlite/xml2)

* import/export fichier
* interroger la structure des données
* notion d'objet R
* notion de data.frame
* notion de vecteur

# Dplyr
* grammaire de base dplyr (`filter`, `select`, `mutate`, `group_by`, `summarise`, `arrange`)

# Tidyr
Principes de [tidyr](https://tidyr.tidyverse.org/)

* colonne = variable
* ligne = observation
* cellule = valeur unique)

## Fonctions de tidyr
* [Transposition](https://tidyr.tidyverse.org/articles/pivot.html) (`pivot_longer`, `pivot_wider`)
* [Carénage](https://tidyr.tidyverse.org/articles/rectangle.html) (JSON -> tibbles : `unnest_longer`, `unnest_wider`, `hoist`)
* [Imbrication](https://tidyr.tidyverse.org/articles/nest.html) (`nest`, `unnest`)
* [Séparation et fusion de colonnes]() (`separate`/`extract`, `unite`)
* [Traitement explicite ou implicite des valeurs manquantes]() (`complete`, `drop_na`, `fill`, `replace_na`)

# Readr

Fonctions pour [importer des données](https://r4ds.had.co.nz/data-import.html) de divers formats, voir la [présentation](https://readr.tidyverse.org/)

Noms de fonction préfixés par `read_`

# Purrr
Programmation fonctionnelle et [itération](https://r4ds.had.co.nz/iteration.html) 

## Fonctions de purrr
[`map()`](https://purrr.tidyverse.org/reference/map.html) et associées

# Tibble

Amélioration du type data.frame (affichage, comportement par défaut, rigueur et gestion des erreurs)

* `as.tibble()` : transformer un objet en tibble
* `tibble()` : créer un tibble à partir d'une liste de variables
* `tribble()` : créer un tibble ligne (row) par ligne

# Stringr

Travailler avec des chaînes de caractères (strings) de façon cohérente (input manquant => output manquant, syntaxe et nom des arguments), voir la [présentation du package](https://stringr.tidyverse.org/)

Nom des fonctions préfixé par `str_`

# Forcats

Fonctions pour les variables catégorielles, voir la [vignette](https://forcats.tidyverse.org/articles/forcats.html)

Nom des fonctions préfixé par `fct_`
