---
title: "Import et Export"
author: "Jocelyn Béziau"
date: 2022-04-10
categories: ["R", "tidyverse", "formation"]
tags: ["R", "intro"]
---
```{r init, message = FALSE, echo = FALSE, warning = FALSE}

library(tidyverse)
library(tibble)
library(rio)
library(palmerpenguins)

knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, cache = TRUE)

set.seed(42)
options(width = 100, 
        repos = "https://cran.rstudio.com/", 
        scipen = 6
        )

```

## Import

Pour la plupart des formats de fichiers (xlsx, ods, csv, txt, sas7bdat, parquet, feather, ...), on peut utiliser `rio::import("nom_du_fichier.extension")` pour en faire un objet R manipulable dans notre environnement.

C'est une surcouche autour des fonctions d'import des packages ad hoc (`data.table::fread()` pour les csv, `readODS::read_ods()` pour les ods, ...)

<!--arrow/disk.frame à la place de feather/fstplyr-->

## Export

De façon symétrique, `rio::export(objetR, "nom_du_fichier.extension")` permet de sauver sur le disque un objet de l'environnement R, à partir des fonctions ad hoc appelées de façon transparente comme pour l'import.

## Stockage intermédiaire

`saveRDS(objetR, "nom_du_fichier.RDS")` pour sauver sur le disque un objet de l'environnement R

`readRDS("nom_du_fichier.RDS")` pour charger cet objet dans l'environnement par la suite. Attention, cela écrase sans préavis tout objet R pré-existant qui porte le même nom que l'objet chargé depuis le .RDS

`save(objetR1, objetR2, ..., file = "nom_du_fichier.RData")` pour sauvegarder plusieurs objets R dans un seul fichier

`load("nom_du_fichier.RData")` pour charger dans l'environnement tous les objets R contenus dans ce fichier. Attention, cela écrasera sans préavis tous les objets R pré-existants qui portent le même nom que l'un des objets chargés depuis le .RData
