---
title: "Chaînes de caractères"
author: "Jocelyn Béziau"
date: 2022-05-07
categories: ["R", "tidyverse", "formation"]
tags: ["R", "intro"]
---

```{r init, message = FALSE, echo = FALSE, warning = FALSE}

library(tidyverse)
library(tibble)
library(rio)
library(palmerpenguins)

knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, cache = TRUE)

set.seed(42)
options(width = 100, 
        repos = "https://cran.rstudio.com/", 
        scipen = 6
        )

```

## Aide-mémoire

**Cas d'utilisation**          |        **Fonction**                    
------------------------------ |----------------------------------------- | 
Concaténation                  | paste0(str~1~,str~2~,str~3~)             |
Nombre de caractères           | str_length(str)                          |
Extraction d'une sous-chaîne   | str_sub(str, pos, pos+len-1)             |
Extraction de la fin           | str_sub(str, pos)                        |
Remplacement de la fin         | str_sub(var, pos) <- new_chaine          | Peut rallonger la chaîne
Réduction des espaces          | str_squish(str)                          |
Elimination des espaces en fin | str_trim(str, side = "right")            |
Elimination des espaces en debut | str_trim(str, side = "left")           |
Mise en majuscules             | str_to_upper(str)                        |
Mise en minuscules             | str_to_lower(str)                        |
Remplacement de caractères     | str_replace_all(old, new, str)           | 
Recherche d'un motif           | str_locate(str,str~2~)                   | Position
"                              | str_detect(str,str~2~)                   | Vrai/Faux
"                              | str_extract(str,str~2~)                  | Chaîne
Retournement                   | stri_reverse(str)                        | {stringi}
Distance                       | stringdist(str,str~2~)                   | {stringdist}

